// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseStatus int32

const (
	ResponseStatus_Ok                  ResponseStatus = 0
	ResponseStatus_InternalServerError ResponseStatus = 1
	ResponseStatus_BadRequest          ResponseStatus = 2
)

var ResponseStatus_name = map[int32]string{
	0: "Ok",
	1: "InternalServerError",
	2: "BadRequest",
}

var ResponseStatus_value = map[string]int32{
	"Ok":                  0,
	"InternalServerError": 1,
	"BadRequest":          2,
}

func (x ResponseStatus) String() string {
	return proto.EnumName(ResponseStatus_name, int32(x))
}

func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type RRType int32

const (
	RRType_A          RRType = 0
	RRType_AAAA       RRType = 1
	RRType_AFSDB      RRType = 2
	RRType_ANY        RRType = 3
	RRType_ATMA       RRType = 4
	RRType_AVC        RRType = 5
	RRType_AXFR       RRType = 6
	RRType_CAA        RRType = 7
	RRType_CDNSKEY    RRType = 8
	RRType_CDS        RRType = 9
	RRType_CERT       RRType = 10
	RRType_CNAME      RRType = 11
	RRType_CSYNC      RRType = 12
	RRType_DHCID      RRType = 13
	RRType_DLV        RRType = 14
	RRType_DNAME      RRType = 15
	RRType_DNSKEY     RRType = 16
	RRType_DS         RRType = 17
	RRType_EID        RRType = 18
	RRType_EUI48      RRType = 19
	RRType_EUI64      RRType = 20
	RRType_GID        RRType = 21
	RRType_GPOS       RRType = 22
	RRType_HINFO      RRType = 23
	RRType_HIP        RRType = 24
	RRType_ISDN       RRType = 25
	RRType_IXFR       RRType = 26
	RRType_KEY        RRType = 27
	RRType_KX         RRType = 28
	RRType_L32        RRType = 29
	RRType_L64        RRType = 30
	RRType_LOC        RRType = 31
	RRType_LP         RRType = 32
	RRType_MAILA      RRType = 33
	RRType_MAILB      RRType = 34
	RRType_MB         RRType = 35
	RRType_MD         RRType = 36
	RRType_MF         RRType = 37
	RRType_MG         RRType = 38
	RRType_MINFO      RRType = 39
	RRType_MR         RRType = 40
	RRType_MX         RRType = 41
	RRType_NAPTR      RRType = 42
	RRType_NID        RRType = 43
	RRType_NIMLOC     RRType = 44
	RRType_NINFO      RRType = 45
	RRType_NS         RRType = 46
	RRType_NSEC       RRType = 47
	RRType_NSEC3      RRType = 48
	RRType_NSEC3PARAM RRType = 49
	RRType_NULL       RRType = 50
	RRType_NXT        RRType = 51
	RRType_None       RRType = 52
	RRType_OPENPGPKEY RRType = 53
	RRType_OPT        RRType = 54
	RRType_PTR        RRType = 55
	RRType_PX         RRType = 56
	RRType_RKEY       RRType = 57
	RRType_RP         RRType = 58
	RRType_RRSIG      RRType = 59
	RRType_RT         RRType = 60
	RRType_Reserved   RRType = 61
	RRType_SIG        RRType = 62
	RRType_SMIMEA     RRType = 63
	RRType_SOA        RRType = 64
	RRType_SPF        RRType = 65
	RRType_SRV        RRType = 66
	RRType_SSHFP      RRType = 67
	RRType_TA         RRType = 68
	RRType_TALINK     RRType = 69
	RRType_TKEY       RRType = 70
	RRType_TLSA       RRType = 71
	RRType_TSIG       RRType = 72
	RRType_TXT        RRType = 73
	RRType_UID        RRType = 74
	RRType_UINFO      RRType = 75
	RRType_UNSPEC     RRType = 76
	RRType_URI        RRType = 77
	RRType_X25        RRType = 78
	RRType_NSAP_PTR   RRType = 79
)

var RRType_name = map[int32]string{
	0:  "A",
	1:  "AAAA",
	2:  "AFSDB",
	3:  "ANY",
	4:  "ATMA",
	5:  "AVC",
	6:  "AXFR",
	7:  "CAA",
	8:  "CDNSKEY",
	9:  "CDS",
	10: "CERT",
	11: "CNAME",
	12: "CSYNC",
	13: "DHCID",
	14: "DLV",
	15: "DNAME",
	16: "DNSKEY",
	17: "DS",
	18: "EID",
	19: "EUI48",
	20: "EUI64",
	21: "GID",
	22: "GPOS",
	23: "HINFO",
	24: "HIP",
	25: "ISDN",
	26: "IXFR",
	27: "KEY",
	28: "KX",
	29: "L32",
	30: "L64",
	31: "LOC",
	32: "LP",
	33: "MAILA",
	34: "MAILB",
	35: "MB",
	36: "MD",
	37: "MF",
	38: "MG",
	39: "MINFO",
	40: "MR",
	41: "MX",
	42: "NAPTR",
	43: "NID",
	44: "NIMLOC",
	45: "NINFO",
	46: "NS",
	47: "NSEC",
	48: "NSEC3",
	49: "NSEC3PARAM",
	50: "NULL",
	51: "NXT",
	52: "None",
	53: "OPENPGPKEY",
	54: "OPT",
	55: "PTR",
	56: "PX",
	57: "RKEY",
	58: "RP",
	59: "RRSIG",
	60: "RT",
	61: "Reserved",
	62: "SIG",
	63: "SMIMEA",
	64: "SOA",
	65: "SPF",
	66: "SRV",
	67: "SSHFP",
	68: "TA",
	69: "TALINK",
	70: "TKEY",
	71: "TLSA",
	72: "TSIG",
	73: "TXT",
	74: "UID",
	75: "UINFO",
	76: "UNSPEC",
	77: "URI",
	78: "X25",
	79: "NSAP_PTR",
}

var RRType_value = map[string]int32{
	"A":          0,
	"AAAA":       1,
	"AFSDB":      2,
	"ANY":        3,
	"ATMA":       4,
	"AVC":        5,
	"AXFR":       6,
	"CAA":        7,
	"CDNSKEY":    8,
	"CDS":        9,
	"CERT":       10,
	"CNAME":      11,
	"CSYNC":      12,
	"DHCID":      13,
	"DLV":        14,
	"DNAME":      15,
	"DNSKEY":     16,
	"DS":         17,
	"EID":        18,
	"EUI48":      19,
	"EUI64":      20,
	"GID":        21,
	"GPOS":       22,
	"HINFO":      23,
	"HIP":        24,
	"ISDN":       25,
	"IXFR":       26,
	"KEY":        27,
	"KX":         28,
	"L32":        29,
	"L64":        30,
	"LOC":        31,
	"LP":         32,
	"MAILA":      33,
	"MAILB":      34,
	"MB":         35,
	"MD":         36,
	"MF":         37,
	"MG":         38,
	"MINFO":      39,
	"MR":         40,
	"MX":         41,
	"NAPTR":      42,
	"NID":        43,
	"NIMLOC":     44,
	"NINFO":      45,
	"NS":         46,
	"NSEC":       47,
	"NSEC3":      48,
	"NSEC3PARAM": 49,
	"NULL":       50,
	"NXT":        51,
	"None":       52,
	"OPENPGPKEY": 53,
	"OPT":        54,
	"PTR":        55,
	"PX":         56,
	"RKEY":       57,
	"RP":         58,
	"RRSIG":      59,
	"RT":         60,
	"Reserved":   61,
	"SIG":        62,
	"SMIMEA":     63,
	"SOA":        64,
	"SPF":        65,
	"SRV":        66,
	"SSHFP":      67,
	"TA":         68,
	"TALINK":     69,
	"TKEY":       70,
	"TLSA":       71,
	"TSIG":       72,
	"TXT":        73,
	"UID":        74,
	"UINFO":      75,
	"UNSPEC":     76,
	"URI":        77,
	"X25":        78,
	"NSAP_PTR":   79,
}

func (x RRType) String() string {
	return proto.EnumName(RRType_name, int32(x))
}

func (RRType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

type CreateAccountResponse_Status int32

const (
	CreateAccountResponse_Ok                  CreateAccountResponse_Status = 0
	CreateAccountResponse_InternalServerError CreateAccountResponse_Status = 1
	CreateAccountResponse_BadRequest          CreateAccountResponse_Status = 2
	CreateAccountResponse_AlreadyExists       CreateAccountResponse_Status = 3
)

var CreateAccountResponse_Status_name = map[int32]string{
	0: "Ok",
	1: "InternalServerError",
	2: "BadRequest",
	3: "AlreadyExists",
}

var CreateAccountResponse_Status_value = map[string]int32{
	"Ok":                  0,
	"InternalServerError": 1,
	"BadRequest":          2,
	"AlreadyExists":       3,
}

func (x CreateAccountResponse_Status) String() string {
	return proto.EnumName(CreateAccountResponse_Status_name, int32(x))
}

func (CreateAccountResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3, 0}
}

type Ping struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Pong struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type CreateAccountRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateAccountResponse struct {
	Status               CreateAccountResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=api.CreateAccountResponse_Status" json:"status,omitempty"`
	Token                string                       `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetStatus() CreateAccountResponse_Status {
	if m != nil {
		return m.Status
	}
	return CreateAccountResponse_Ok
}

func (m *CreateAccountResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetTokenRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetTokenResponse struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
	Token                string         `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_Ok
}

func (m *GetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ChangePasswordRequest struct {
	Pass                 string   `protobuf:"bytes,1,opt,name=pass,proto3" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type ChangePasswordResponse struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_Ok
}

type InitZoneRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitZoneRequest) Reset()         { *m = InitZoneRequest{} }
func (m *InitZoneRequest) String() string { return proto.CompactTextString(m) }
func (*InitZoneRequest) ProtoMessage()    {}
func (*InitZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *InitZoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitZoneRequest.Unmarshal(m, b)
}
func (m *InitZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitZoneRequest.Marshal(b, m, deterministic)
}
func (m *InitZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitZoneRequest.Merge(m, src)
}
func (m *InitZoneRequest) XXX_Size() int {
	return xxx_messageInfo_InitZoneRequest.Size(m)
}
func (m *InitZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitZoneRequest proto.InternalMessageInfo

func (m *InitZoneRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type InitZoneResponse struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InitZoneResponse) Reset()         { *m = InitZoneResponse{} }
func (m *InitZoneResponse) String() string { return proto.CompactTextString(m) }
func (*InitZoneResponse) ProtoMessage()    {}
func (*InitZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *InitZoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitZoneResponse.Unmarshal(m, b)
}
func (m *InitZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitZoneResponse.Marshal(b, m, deterministic)
}
func (m *InitZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitZoneResponse.Merge(m, src)
}
func (m *InitZoneResponse) XXX_Size() int {
	return xxx_messageInfo_InitZoneResponse.Size(m)
}
func (m *InitZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitZoneResponse proto.InternalMessageInfo

func (m *InitZoneResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_Ok
}

type RemoveZoneRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveZoneRequest) Reset()         { *m = RemoveZoneRequest{} }
func (m *RemoveZoneRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveZoneRequest) ProtoMessage()    {}
func (*RemoveZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *RemoveZoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveZoneRequest.Unmarshal(m, b)
}
func (m *RemoveZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveZoneRequest.Marshal(b, m, deterministic)
}
func (m *RemoveZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveZoneRequest.Merge(m, src)
}
func (m *RemoveZoneRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveZoneRequest.Size(m)
}
func (m *RemoveZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveZoneRequest proto.InternalMessageInfo

func (m *RemoveZoneRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type RemoveZoneResponse struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RemoveZoneResponse) Reset()         { *m = RemoveZoneResponse{} }
func (m *RemoveZoneResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveZoneResponse) ProtoMessage()    {}
func (*RemoveZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *RemoveZoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveZoneResponse.Unmarshal(m, b)
}
func (m *RemoveZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveZoneResponse.Marshal(b, m, deterministic)
}
func (m *RemoveZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveZoneResponse.Merge(m, src)
}
func (m *RemoveZoneResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveZoneResponse.Size(m)
}
func (m *RemoveZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveZoneResponse proto.InternalMessageInfo

func (m *RemoveZoneResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_Ok
}

type AddRecordRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Origin               string   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Type                 RRType   `protobuf:"varint,3,opt,name=type,proto3,enum=api.RRType" json:"type,omitempty"`
	Ttl                  int64    `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRecordRequest) Reset()         { *m = AddRecordRequest{} }
func (m *AddRecordRequest) String() string { return proto.CompactTextString(m) }
func (*AddRecordRequest) ProtoMessage()    {}
func (*AddRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *AddRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecordRequest.Unmarshal(m, b)
}
func (m *AddRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecordRequest.Marshal(b, m, deterministic)
}
func (m *AddRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecordRequest.Merge(m, src)
}
func (m *AddRecordRequest) XXX_Size() int {
	return xxx_messageInfo_AddRecordRequest.Size(m)
}
func (m *AddRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecordRequest proto.InternalMessageInfo

func (m *AddRecordRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddRecordRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *AddRecordRequest) GetType() RRType {
	if m != nil {
		return m.Type
	}
	return RRType_A
}

func (m *AddRecordRequest) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *AddRecordRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type AddRecordResponse struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddRecordResponse) Reset()         { *m = AddRecordResponse{} }
func (m *AddRecordResponse) String() string { return proto.CompactTextString(m) }
func (*AddRecordResponse) ProtoMessage()    {}
func (*AddRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *AddRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecordResponse.Unmarshal(m, b)
}
func (m *AddRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecordResponse.Marshal(b, m, deterministic)
}
func (m *AddRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecordResponse.Merge(m, src)
}
func (m *AddRecordResponse) XXX_Size() int {
	return xxx_messageInfo_AddRecordResponse.Size(m)
}
func (m *AddRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecordResponse proto.InternalMessageInfo

func (m *AddRecordResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_Ok
}

type RemoveRecordRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Origin               string   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Type                 RRType   `protobuf:"varint,3,opt,name=type,proto3,enum=api.RRType" json:"type,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRecordRequest) Reset()         { *m = RemoveRecordRequest{} }
func (m *RemoveRecordRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRecordRequest) ProtoMessage()    {}
func (*RemoveRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *RemoveRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRecordRequest.Unmarshal(m, b)
}
func (m *RemoveRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRecordRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRecordRequest.Merge(m, src)
}
func (m *RemoveRecordRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRecordRequest.Size(m)
}
func (m *RemoveRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRecordRequest proto.InternalMessageInfo

func (m *RemoveRecordRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoveRecordRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *RemoveRecordRequest) GetType() RRType {
	if m != nil {
		return m.Type
	}
	return RRType_A
}

func (m *RemoveRecordRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type RemoveRecordResponse struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RemoveRecordResponse) Reset()         { *m = RemoveRecordResponse{} }
func (m *RemoveRecordResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveRecordResponse) ProtoMessage()    {}
func (*RemoveRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *RemoveRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRecordResponse.Unmarshal(m, b)
}
func (m *RemoveRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRecordResponse.Marshal(b, m, deterministic)
}
func (m *RemoveRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRecordResponse.Merge(m, src)
}
func (m *RemoveRecordResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveRecordResponse.Size(m)
}
func (m *RemoveRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRecordResponse proto.InternalMessageInfo

func (m *RemoveRecordResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_Ok
}

type UpdateRecordRequest struct {
	Origin               string                      `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Target               *UpdateRecordRequest_Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Source               *UpdateRecordRequest_Source `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *UpdateRecordRequest) Reset()         { *m = UpdateRecordRequest{} }
func (m *UpdateRecordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRecordRequest) ProtoMessage()    {}
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *UpdateRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecordRequest.Unmarshal(m, b)
}
func (m *UpdateRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecordRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecordRequest.Merge(m, src)
}
func (m *UpdateRecordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRecordRequest.Size(m)
}
func (m *UpdateRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecordRequest proto.InternalMessageInfo

func (m *UpdateRecordRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *UpdateRecordRequest) GetTarget() *UpdateRecordRequest_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *UpdateRecordRequest) GetSource() *UpdateRecordRequest_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type UpdateRecordRequest_Target struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 RRType   `protobuf:"varint,2,opt,name=type,proto3,enum=api.RRType" json:"type,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecordRequest_Target) Reset()         { *m = UpdateRecordRequest_Target{} }
func (m *UpdateRecordRequest_Target) String() string { return proto.CompactTextString(m) }
func (*UpdateRecordRequest_Target) ProtoMessage()    {}
func (*UpdateRecordRequest_Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16, 0}
}

func (m *UpdateRecordRequest_Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecordRequest_Target.Unmarshal(m, b)
}
func (m *UpdateRecordRequest_Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecordRequest_Target.Marshal(b, m, deterministic)
}
func (m *UpdateRecordRequest_Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecordRequest_Target.Merge(m, src)
}
func (m *UpdateRecordRequest_Target) XXX_Size() int {
	return xxx_messageInfo_UpdateRecordRequest_Target.Size(m)
}
func (m *UpdateRecordRequest_Target) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecordRequest_Target.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecordRequest_Target proto.InternalMessageInfo

func (m *UpdateRecordRequest_Target) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRecordRequest_Target) GetType() RRType {
	if m != nil {
		return m.Type
	}
	return RRType_A
}

func (m *UpdateRecordRequest_Target) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UpdateRecordRequest_Source struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 RRType   `protobuf:"varint,2,opt,name=type,proto3,enum=api.RRType" json:"type,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Ttl                  int64    `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecordRequest_Source) Reset()         { *m = UpdateRecordRequest_Source{} }
func (m *UpdateRecordRequest_Source) String() string { return proto.CompactTextString(m) }
func (*UpdateRecordRequest_Source) ProtoMessage()    {}
func (*UpdateRecordRequest_Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16, 1}
}

func (m *UpdateRecordRequest_Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecordRequest_Source.Unmarshal(m, b)
}
func (m *UpdateRecordRequest_Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecordRequest_Source.Marshal(b, m, deterministic)
}
func (m *UpdateRecordRequest_Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecordRequest_Source.Merge(m, src)
}
func (m *UpdateRecordRequest_Source) XXX_Size() int {
	return xxx_messageInfo_UpdateRecordRequest_Source.Size(m)
}
func (m *UpdateRecordRequest_Source) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecordRequest_Source.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecordRequest_Source proto.InternalMessageInfo

func (m *UpdateRecordRequest_Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRecordRequest_Source) GetType() RRType {
	if m != nil {
		return m.Type
	}
	return RRType_A
}

func (m *UpdateRecordRequest_Source) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdateRecordRequest_Source) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type UpdateRecordResponse struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateRecordResponse) Reset()         { *m = UpdateRecordResponse{} }
func (m *UpdateRecordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRecordResponse) ProtoMessage()    {}
func (*UpdateRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *UpdateRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecordResponse.Unmarshal(m, b)
}
func (m *UpdateRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecordResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecordResponse.Merge(m, src)
}
func (m *UpdateRecordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRecordResponse.Size(m)
}
func (m *UpdateRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecordResponse proto.InternalMessageInfo

func (m *UpdateRecordResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_Ok
}

type GetDomainsResponse struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
	Domains              []*Domain      `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetDomainsResponse) Reset()         { *m = GetDomainsResponse{} }
func (m *GetDomainsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDomainsResponse) ProtoMessage()    {}
func (*GetDomainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *GetDomainsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDomainsResponse.Unmarshal(m, b)
}
func (m *GetDomainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDomainsResponse.Marshal(b, m, deterministic)
}
func (m *GetDomainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDomainsResponse.Merge(m, src)
}
func (m *GetDomainsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDomainsResponse.Size(m)
}
func (m *GetDomainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDomainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDomainsResponse proto.InternalMessageInfo

func (m *GetDomainsResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_Ok
}

func (m *GetDomainsResponse) GetDomains() []*Domain {
	if m != nil {
		return m.Domains
	}
	return nil
}

type Domain struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Domain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetRecordsRequest struct {
	Origin               string   `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordsRequest) Reset()         { *m = GetRecordsRequest{} }
func (m *GetRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordsRequest) ProtoMessage()    {}
func (*GetRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *GetRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordsRequest.Unmarshal(m, b)
}
func (m *GetRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordsRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordsRequest.Merge(m, src)
}
func (m *GetRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordsRequest.Size(m)
}
func (m *GetRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordsRequest proto.InternalMessageInfo

func (m *GetRecordsRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type GetRecordsResponse struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
	Records              []*Record      `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRecordsResponse) Reset()         { *m = GetRecordsResponse{} }
func (m *GetRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecordsResponse) ProtoMessage()    {}
func (*GetRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *GetRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordsResponse.Unmarshal(m, b)
}
func (m *GetRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordsResponse.Marshal(b, m, deterministic)
}
func (m *GetRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordsResponse.Merge(m, src)
}
func (m *GetRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecordsResponse.Size(m)
}
func (m *GetRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordsResponse proto.InternalMessageInfo

func (m *GetRecordsResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_Ok
}

func (m *GetRecordsResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Record struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 RRType   `protobuf:"varint,2,opt,name=type,proto3,enum=api.RRType" json:"type,omitempty"`
	Ttl                  int64    `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Record) GetType() RRType {
	if m != nil {
		return m.Type
	}
	return RRType_A
}

func (m *Record) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *Record) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.ResponseStatus", ResponseStatus_name, ResponseStatus_value)
	proto.RegisterEnum("api.RRType", RRType_name, RRType_value)
	proto.RegisterEnum("api.CreateAccountResponse_Status", CreateAccountResponse_Status_name, CreateAccountResponse_Status_value)
	proto.RegisterType((*Ping)(nil), "api.Ping")
	proto.RegisterType((*Pong)(nil), "api.Pong")
	proto.RegisterType((*CreateAccountRequest)(nil), "api.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "api.CreateAccountResponse")
	proto.RegisterType((*GetTokenRequest)(nil), "api.getTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "api.getTokenResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "api.changePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "api.changePasswordResponse")
	proto.RegisterType((*InitZoneRequest)(nil), "api.InitZoneRequest")
	proto.RegisterType((*InitZoneResponse)(nil), "api.InitZoneResponse")
	proto.RegisterType((*RemoveZoneRequest)(nil), "api.RemoveZoneRequest")
	proto.RegisterType((*RemoveZoneResponse)(nil), "api.RemoveZoneResponse")
	proto.RegisterType((*AddRecordRequest)(nil), "api.AddRecordRequest")
	proto.RegisterType((*AddRecordResponse)(nil), "api.AddRecordResponse")
	proto.RegisterType((*RemoveRecordRequest)(nil), "api.RemoveRecordRequest")
	proto.RegisterType((*RemoveRecordResponse)(nil), "api.RemoveRecordResponse")
	proto.RegisterType((*UpdateRecordRequest)(nil), "api.UpdateRecordRequest")
	proto.RegisterType((*UpdateRecordRequest_Target)(nil), "api.UpdateRecordRequest.Target")
	proto.RegisterType((*UpdateRecordRequest_Source)(nil), "api.UpdateRecordRequest.Source")
	proto.RegisterType((*UpdateRecordResponse)(nil), "api.UpdateRecordResponse")
	proto.RegisterType((*GetDomainsResponse)(nil), "api.GetDomainsResponse")
	proto.RegisterType((*Domain)(nil), "api.Domain")
	proto.RegisterType((*GetRecordsRequest)(nil), "api.GetRecordsRequest")
	proto.RegisterType((*GetRecordsResponse)(nil), "api.GetRecordsResponse")
	proto.RegisterType((*Record)(nil), "api.Record")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x6d, 0x73, 0xdb, 0xc4,
	0x13, 0xaf, 0x1f, 0xe2, 0x24, 0x9b, 0x36, 0xdd, 0x5c, 0x1e, 0xea, 0xba, 0xfd, 0xff, 0x9b, 0x1a,
	0x0a, 0x69, 0x53, 0x5c, 0x48, 0xd2, 0x47, 0x28, 0xed, 0x45, 0x92, 0x1d, 0x11, 0x5b, 0xd6, 0x48,
	0x4e, 0x49, 0x79, 0xc3, 0xa8, 0xf6, 0xe1, 0x6a, 0x9a, 0x48, 0x46, 0x52, 0x4a, 0x33, 0xc3, 0x37,
	0xe0, 0x63, 0xf0, 0x11, 0x98, 0xe1, 0x0b, 0xf1, 0x45, 0x98, 0x3d, 0x9d, 0x92, 0xd8, 0x71, 0xa1,
	0x78, 0xe0, 0x95, 0xf6, 0xf6, 0xe1, 0xf7, 0xdb, 0xdd, 0xd3, 0xe9, 0x56, 0x30, 0xeb, 0x0d, 0xfc,
	0xda, 0x20, 0x0a, 0x93, 0x90, 0x15, 0xbc, 0x81, 0x5f, 0xb9, 0xd6, 0x0f, 0xc3, 0xfe, 0x81, 0xb8,
	0x27, 0x55, 0xaf, 0x8e, 0x7e, 0xb8, 0x27, 0x0e, 0x07, 0xc9, 0x71, 0xea, 0x51, 0xad, 0x40, 0xd1,
	0xf6, 0x83, 0x3e, 0x63, 0x50, 0x4c, 0xc4, 0xbb, 0xa4, 0x9c, 0x5b, 0xcd, 0xad, 0xcd, 0x3a, 0x52,
	0x96, 0xb6, 0xf0, 0x3d, 0xb6, 0x1d, 0x58, 0xd2, 0x22, 0xe1, 0x25, 0x82, 0x77, 0xbb, 0xe1, 0x51,
	0x90, 0x38, 0xe2, 0xc7, 0x23, 0x11, 0x27, 0x6c, 0x09, 0xa6, 0xc4, 0xa1, 0xe7, 0x1f, 0x28, 0xe7,
	0x74, 0xc1, 0x2a, 0x30, 0x33, 0xf0, 0xe2, 0xf8, 0xa7, 0x30, 0xea, 0x95, 0xf3, 0xd2, 0x70, 0xb2,
	0xae, 0xfe, 0x9e, 0x83, 0xe5, 0x11, 0xa8, 0x78, 0x10, 0x06, 0xb1, 0x60, 0x8f, 0xa1, 0x14, 0x27,
	0x5e, 0x72, 0x14, 0x4b, 0xb0, 0xf9, 0x8d, 0x9b, 0x35, 0xaa, 0x6c, 0xac, 0x6f, 0xcd, 0x95, 0x8e,
	0x8e, 0x0a, 0xa0, 0x34, 0x92, 0xf0, 0x8d, 0x08, 0x14, 0x5b, 0xba, 0xa8, 0x36, 0xa1, 0x94, 0xfa,
	0xb1, 0x12, 0xe4, 0xdb, 0x6f, 0xf0, 0x02, 0xbb, 0x02, 0x8b, 0x66, 0x90, 0x88, 0x28, 0xf0, 0x0e,
	0x5c, 0x11, 0xbd, 0x15, 0x91, 0x11, 0x45, 0x61, 0x84, 0x39, 0x36, 0x0f, 0xb0, 0xed, 0xf5, 0x54,
	0x55, 0x98, 0x67, 0x0b, 0x70, 0x89, 0x1f, 0x44, 0xc2, 0xeb, 0x1d, 0x1b, 0xef, 0xfc, 0x38, 0x89,
	0xb1, 0x50, 0xd5, 0xe0, 0x72, 0x5f, 0x24, 0x1d, 0x42, 0x9e, 0xbc, 0xfa, 0x3d, 0xc0, 0x53, 0x10,
	0x55, 0xf7, 0xfa, 0x48, 0xdd, 0x8b, 0xb2, 0xee, 0xcc, 0xfc, 0x41, 0x95, 0xae, 0xc3, 0x72, 0xf7,
	0xb5, 0x17, 0xf4, 0x85, 0xad, 0x88, 0xb2, 0x0c, 0x19, 0x14, 0x89, 0x3b, 0xdb, 0x4b, 0x92, 0xab,
	0x06, 0xac, 0x8c, 0x3a, 0x4f, 0x90, 0x49, 0xf5, 0x36, 0x5c, 0x36, 0x03, 0x3f, 0xf9, 0x2e, 0x0c,
	0x44, 0xc6, 0xb6, 0x02, 0xa5, 0x5e, 0x78, 0xe8, 0xf9, 0x81, 0xe2, 0x53, 0xab, 0xea, 0x33, 0xc0,
	0x53, 0xd7, 0x49, 0xb8, 0xd6, 0x61, 0xc1, 0x11, 0x87, 0xe1, 0x5b, 0xf1, 0x21, 0x6c, 0x1c, 0xd8,
	0x59, 0xe7, 0x49, 0xf8, 0x7e, 0xc9, 0x01, 0xf2, 0x5e, 0xcf, 0x11, 0xdd, 0xe1, 0x5e, 0x06, 0xde,
	0xa1, 0xc8, 0x7a, 0x49, 0x32, 0xe5, 0x10, 0x46, 0x7e, 0xdf, 0xcf, 0xf6, 0x43, 0xad, 0xd8, 0x0d,
	0x28, 0x26, 0xc7, 0x03, 0x51, 0x2e, 0x48, 0xae, 0xb9, 0x94, 0xcb, 0xe9, 0x1c, 0x0f, 0x84, 0x23,
	0x0d, 0x0c, 0xa1, 0x90, 0x24, 0x07, 0xe5, 0xe2, 0x6a, 0x6e, 0xad, 0xe0, 0x90, 0xc8, 0xca, 0x30,
	0xdd, 0x0d, 0x83, 0x44, 0x04, 0x49, 0x79, 0x4a, 0x62, 0x65, 0xcb, 0xea, 0x73, 0x58, 0x38, 0x93,
	0xcc, 0x24, 0xf5, 0xfc, 0x0c, 0x8b, 0x69, 0x4b, 0xfe, 0xc3, 0x8a, 0xce, 0xe4, 0x5f, 0x1c, 0xce,
	0x5f, 0x83, 0xa5, 0x61, 0xf6, 0x49, 0x4a, 0xf8, 0x23, 0x0f, 0x8b, 0x7b, 0x83, 0x9e, 0x97, 0x8c,
	0xd4, 0x70, 0x9a, 0x6f, 0x6e, 0x28, 0xdf, 0x87, 0x50, 0x4a, 0xbc, 0xa8, 0x2f, 0x12, 0x59, 0xc7,
	0xdc, 0xc6, 0x0d, 0x09, 0x3e, 0x06, 0xa1, 0xd6, 0x91, 0x6e, 0x8e, 0x72, 0xa7, 0xc0, 0x38, 0x3c,
	0x8a, 0xba, 0x69, 0xa9, 0x7f, 0x15, 0xe8, 0x4a, 0x37, 0x47, 0xb9, 0x57, 0xbe, 0x85, 0x52, 0x0a,
	0x35, 0xb6, 0xaf, 0x59, 0xff, 0xf2, 0x1f, 0xd0, 0xbf, 0xc2, 0x50, 0xff, 0x2a, 0x3e, 0x94, 0x52,
	0xaa, 0x7f, 0x19, 0xf8, 0xfc, 0x4b, 0x48, 0x5b, 0x35, 0x5c, 0xe9, 0x24, 0x5b, 0xf5, 0x1a, 0x58,
	0x43, 0x24, 0xba, 0x3c, 0x8d, 0xf1, 0x64, 0x9f, 0xb9, 0x5b, 0x30, 0x9d, 0x9e, 0xe6, 0xb8, 0x9c,
	0x5f, 0x2d, 0xac, 0xcd, 0xa9, 0xba, 0x52, 0x4c, 0x27, 0xb3, 0x55, 0xef, 0x42, 0x29, 0x55, 0xb1,
	0x79, 0xc8, 0xfb, 0x3d, 0x89, 0x5c, 0x70, 0xf2, 0x7e, 0xef, 0xa4, 0x53, 0xf9, 0xd3, 0x4e, 0xd1,
	0x57, 0xa4, 0x21, 0x92, 0xb4, 0xb2, 0xf8, 0x6f, 0xde, 0x1f, 0x55, 0xc4, 0x89, 0xf3, 0x84, 0x45,
	0x44, 0x69, 0xfc, 0x50, 0x11, 0xaa, 0xb5, 0x99, 0xad, 0xea, 0x43, 0x29, 0x55, 0x4d, 0xb6, 0xbd,
	0x6a, 0x13, 0x0b, 0x63, 0xbf, 0x24, 0xc3, 0x27, 0xf1, 0x0e, 0x87, 0xf9, 0xe1, 0x5c, 0xff, 0xf1,
	0xcd, 0x78, 0xe7, 0xd7, 0x12, 0x94, 0x52, 0x7e, 0x36, 0x05, 0x39, 0x8e, 0x17, 0xd8, 0x0c, 0x14,
	0x39, 0xe7, 0x1c, 0x73, 0x6c, 0x16, 0xa6, 0x78, 0xdd, 0xd5, 0xb7, 0x31, 0xcf, 0xa6, 0xa1, 0xc0,
	0xad, 0x97, 0x58, 0x90, 0xd6, 0x4e, 0x8b, 0x63, 0x51, 0xaa, 0x5e, 0x68, 0x38, 0x25, 0x55, 0xfb,
	0x75, 0x07, 0x4b, 0xa4, 0xd2, 0x38, 0xc7, 0x69, 0x36, 0x07, 0xd3, 0x9a, 0x6e, 0xb9, 0xbb, 0xc6,
	0x4b, 0x9c, 0x91, 0x5a, 0xdd, 0xc5, 0x59, 0x72, 0xd4, 0x0c, 0xa7, 0x83, 0x40, 0xc8, 0x9a, 0xc5,
	0x5b, 0x06, 0xce, 0x49, 0xd1, 0x7d, 0x69, 0x69, 0x78, 0x91, 0x44, 0x7d, 0x47, 0x33, 0x75, 0xbc,
	0x44, 0x31, 0x7a, 0xf3, 0x05, 0xce, 0x4b, 0x9d, 0xf4, 0xbc, 0xcc, 0x00, 0x4a, 0x0a, 0x13, 0xa9,
	0x4e, 0xdd, 0xc5, 0x05, 0xf2, 0x33, 0x4c, 0x1d, 0x19, 0xf9, 0x19, 0x7b, 0xe6, 0xd6, 0x23, 0x5c,
	0x54, 0xe2, 0x83, 0x2d, 0x5c, 0x22, 0x73, 0xc3, 0xd4, 0x71, 0x99, 0xa8, 0x1b, 0x76, 0xdb, 0xc5,
	0x15, 0xb2, 0xee, 0x98, 0x56, 0xbd, 0x8d, 0x57, 0xc8, 0xba, 0x63, 0xda, 0x58, 0x26, 0xab, 0xe9,
	0xea, 0x16, 0x5e, 0x95, 0x12, 0xd5, 0x52, 0x21, 0x23, 0x51, 0x5d, 0x23, 0xaa, 0xdd, 0x7d, 0xbc,
	0x4e, 0x8a, 0xe6, 0xe6, 0x06, 0xfe, 0x4f, 0x0a, 0x0f, 0xb6, 0xf0, 0xff, 0x52, 0x68, 0x6b, 0x78,
	0x83, 0x5c, 0x9a, 0x36, 0xae, 0x12, 0x76, 0x8b, 0x9b, 0x4d, 0x8e, 0x37, 0x33, 0x71, 0x1b, 0xab,
	0x64, 0x6d, 0x6d, 0xe3, 0x47, 0xf2, 0xa9, 0xe3, 0xc7, 0xf2, 0x59, 0xc7, 0x5b, 0xf2, 0xd9, 0xc0,
	0x4f, 0xa4, 0xab, 0xcc, 0xe8, 0x53, 0xa9, 0x72, 0x70, 0x4d, 0x3e, 0xf7, 0xf1, 0x36, 0x99, 0x2c,
	0x6e, 0x77, 0x1c, 0xbc, 0x43, 0x64, 0x96, 0xa9, 0xe3, 0x3a, 0xb5, 0xc1, 0x32, 0x5b, 0x44, 0x7c,
	0x57, 0xda, 0x65, 0xe8, 0x67, 0x14, 0x62, 0xb9, 0x58, 0xa3, 0x0a, 0x2c, 0xd7, 0xd0, 0xf0, 0x9e,
	0x34, 0xba, 0x86, 0xb6, 0x89, 0x9f, 0xd3, 0xae, 0x4b, 0xd1, 0xe6, 0x0e, 0x6f, 0xe1, 0x17, 0xd2,
	0x69, 0xaf, 0xd9, 0xc4, 0x0d, 0x09, 0xbb, 0xdf, 0xc1, 0x4d, 0xa9, 0x0a, 0x03, 0x81, 0x5b, 0xe4,
	0xdc, 0xb6, 0x0d, 0xcb, 0x6e, 0xd8, 0xd4, 0x80, 0xfb, 0xe4, 0xd2, 0xb6, 0x3b, 0xf8, 0x80, 0x04,
	0xca, 0xe5, 0x21, 0x71, 0xd9, 0xfb, 0xf8, 0x88, 0x62, 0x1c, 0xf2, 0x79, 0x4c, 0x1a, 0xc7, 0xc6,
	0x27, 0xc4, 0xe9, 0x38, 0xae, 0xd9, 0xc0, 0x2f, 0xa5, 0xaa, 0x83, 0x5f, 0xb1, 0x8b, 0x30, 0xe3,
	0x88, 0x98, 0x5e, 0xc2, 0x1e, 0x3e, 0x25, 0x0c, 0x32, 0x7f, 0x4d, 0x65, 0xb8, 0x2d, 0xb3, 0x65,
	0x70, 0x7c, 0x26, 0x95, 0x6d, 0x8e, 0xcf, 0xa5, 0x60, 0xd7, 0x91, 0x4b, 0xc1, 0x79, 0x81, 0xdb,
	0x04, 0xe8, 0xba, 0x3b, 0x75, 0x1b, 0x35, 0x02, 0xec, 0x70, 0xd4, 0x29, 0xb2, 0xc3, 0x9b, 0xa6,
	0xb5, 0x8b, 0x06, 0x65, 0xd0, 0xa1, 0x0c, 0xea, 0x52, 0x6a, 0xba, 0x1c, 0x1b, 0x52, 0x22, 0x8e,
	0x1d, 0x42, 0xe9, 0xec, 0x77, 0xd0, 0x24, 0x61, 0xcf, 0xd4, 0xf1, 0x1b, 0x82, 0xdb, 0x93, 0x0d,
	0xdb, 0x25, 0x98, 0x3d, 0xcb, 0xb5, 0x0d, 0x0d, 0x9b, 0xd2, 0xee, 0x98, 0xd8, 0x22, 0x61, 0x7f,
	0xe3, 0x3e, 0x5a, 0x94, 0xb5, 0xe5, 0x72, 0xfb, 0x7b, 0x2a, 0xb8, 0xbd, 0xf1, 0xdb, 0x14, 0xcc,
	0xd9, 0xbd, 0x20, 0xa6, 0xb3, 0xe4, 0x77, 0x05, 0xbb, 0x0e, 0xc5, 0x01, 0xcd, 0xdd, 0xb3, 0xf2,
	0xfc, 0xd2, 0x08, 0x5e, 0x51, 0x22, 0x4d, 0xdc, 0x75, 0xb8, 0xd4, 0x3d, 0x3b, 0xe6, 0xb2, 0xab,
	0xe3, 0x46, 0x5f, 0x79, 0x02, 0x2b, 0x95, 0xf7, 0x4f, 0xc5, 0xec, 0x21, 0xcc, 0x64, 0xd3, 0x25,
	0x5b, 0x92, 0x7e, 0x23, 0x13, 0x6b, 0x65, 0x79, 0x44, 0xab, 0x02, 0x4d, 0x98, 0x1f, 0x1e, 0x09,
	0x59, 0x4a, 0x33, 0x76, 0xa8, 0xac, 0x5c, 0x1b, 0x6b, 0x3b, 0xcd, 0xc1, 0x57, 0xb3, 0x9e, 0xca,
	0x61, 0x64, 0x4a, 0x54, 0x39, 0x9c, 0x1b, 0x08, 0x9f, 0x02, 0x44, 0x27, 0x63, 0x1b, 0x5b, 0x51,
	0x9f, 0xca, 0x91, 0xa1, 0xaf, 0x72, 0xe5, 0x9c, 0x5e, 0x85, 0x3f, 0x81, 0x59, 0x2f, 0x1b, 0x92,
	0x58, 0x4a, 0x31, 0x3a, 0xc1, 0x55, 0x56, 0x46, 0xd5, 0x2a, 0x56, 0x83, 0x8b, 0xd1, 0x99, 0x01,
	0x85, 0x95, 0xcf, 0x90, 0x0c, 0x23, 0x5c, 0x1d, 0x63, 0x39, 0x05, 0x39, 0x3a, 0x73, 0x75, 0x2a,
	0x90, 0x31, 0x73, 0x83, 0x02, 0x19, 0x7b, 0xcf, 0x3e, 0x05, 0xe8, 0x9f, 0x5c, 0x9d, 0x6c, 0xa5,
	0x96, 0xfe, 0xcb, 0xd5, 0xb2, 0x7f, 0xb9, 0x9a, 0x41, 0xff, 0x72, 0xaa, 0x09, 0x63, 0xee, 0xd8,
	0x34, 0x5c, 0x5d, 0x5a, 0xaa, 0x87, 0xe7, 0xae, 0xbc, 0xd3, 0xf0, 0x91, 0xdb, 0xed, 0x55, 0x49,
	0xf2, 0x6c, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0x59, 0x0c, 0x9c, 0xb2, 0x53, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PdnsServiceClient is the client API for PdnsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PdnsServiceClient interface {
	Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	InitZone(ctx context.Context, in *InitZoneRequest, opts ...grpc.CallOption) (*InitZoneResponse, error)
	RemoveZone(ctx context.Context, in *RemoveZoneRequest, opts ...grpc.CallOption) (*RemoveZoneResponse, error)
	AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error)
	RemoveRecord(ctx context.Context, in *RemoveRecordRequest, opts ...grpc.CallOption) (*RemoveRecordResponse, error)
	UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordResponse, error)
	GetDomains(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetDomainsResponse, error)
	GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (*GetRecordsResponse, error)
}

type pdnsServiceClient struct {
	cc *grpc.ClientConn
}

func NewPdnsServiceClient(cc *grpc.ClientConn) PdnsServiceClient {
	return &pdnsServiceClient{cc}
}

func (c *pdnsServiceClient) Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/api.PdnsService/ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdnsServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/api.PdnsService/createAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdnsServiceClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/api.PdnsService/getToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdnsServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/api.PdnsService/changePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdnsServiceClient) InitZone(ctx context.Context, in *InitZoneRequest, opts ...grpc.CallOption) (*InitZoneResponse, error) {
	out := new(InitZoneResponse)
	err := c.cc.Invoke(ctx, "/api.PdnsService/initZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdnsServiceClient) RemoveZone(ctx context.Context, in *RemoveZoneRequest, opts ...grpc.CallOption) (*RemoveZoneResponse, error) {
	out := new(RemoveZoneResponse)
	err := c.cc.Invoke(ctx, "/api.PdnsService/removeZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdnsServiceClient) AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	out := new(AddRecordResponse)
	err := c.cc.Invoke(ctx, "/api.PdnsService/addRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdnsServiceClient) RemoveRecord(ctx context.Context, in *RemoveRecordRequest, opts ...grpc.CallOption) (*RemoveRecordResponse, error) {
	out := new(RemoveRecordResponse)
	err := c.cc.Invoke(ctx, "/api.PdnsService/removeRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdnsServiceClient) UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordResponse, error) {
	out := new(UpdateRecordResponse)
	err := c.cc.Invoke(ctx, "/api.PdnsService/updateRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdnsServiceClient) GetDomains(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetDomainsResponse, error) {
	out := new(GetDomainsResponse)
	err := c.cc.Invoke(ctx, "/api.PdnsService/getDomains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdnsServiceClient) GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (*GetRecordsResponse, error) {
	out := new(GetRecordsResponse)
	err := c.cc.Invoke(ctx, "/api.PdnsService/getRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdnsServiceServer is the server API for PdnsService service.
type PdnsServiceServer interface {
	Ping(context.Context, *Ping) (*Pong, error)
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	InitZone(context.Context, *InitZoneRequest) (*InitZoneResponse, error)
	RemoveZone(context.Context, *RemoveZoneRequest) (*RemoveZoneResponse, error)
	AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error)
	RemoveRecord(context.Context, *RemoveRecordRequest) (*RemoveRecordResponse, error)
	UpdateRecord(context.Context, *UpdateRecordRequest) (*UpdateRecordResponse, error)
	GetDomains(context.Context, *empty.Empty) (*GetDomainsResponse, error)
	GetRecords(context.Context, *GetRecordsRequest) (*GetRecordsResponse, error)
}

// UnimplementedPdnsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPdnsServiceServer struct {
}

func (*UnimplementedPdnsServiceServer) Ping(ctx context.Context, req *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedPdnsServiceServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedPdnsServiceServer) GetToken(ctx context.Context, req *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (*UnimplementedPdnsServiceServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedPdnsServiceServer) InitZone(ctx context.Context, req *InitZoneRequest) (*InitZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitZone not implemented")
}
func (*UnimplementedPdnsServiceServer) RemoveZone(ctx context.Context, req *RemoveZoneRequest) (*RemoveZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveZone not implemented")
}
func (*UnimplementedPdnsServiceServer) AddRecord(ctx context.Context, req *AddRecordRequest) (*AddRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRecord not implemented")
}
func (*UnimplementedPdnsServiceServer) RemoveRecord(ctx context.Context, req *RemoveRecordRequest) (*RemoveRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRecord not implemented")
}
func (*UnimplementedPdnsServiceServer) UpdateRecord(ctx context.Context, req *UpdateRecordRequest) (*UpdateRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRecord not implemented")
}
func (*UnimplementedPdnsServiceServer) GetDomains(ctx context.Context, req *empty.Empty) (*GetDomainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDomains not implemented")
}
func (*UnimplementedPdnsServiceServer) GetRecords(ctx context.Context, req *GetRecordsRequest) (*GetRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecords not implemented")
}

func RegisterPdnsServiceServer(s *grpc.Server, srv PdnsServiceServer) {
	s.RegisterService(&_PdnsService_serviceDesc, srv)
}

func _PdnsService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).Ping(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdnsService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdnsService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdnsService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdnsService_InitZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).InitZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/InitZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).InitZone(ctx, req.(*InitZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdnsService_RemoveZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).RemoveZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/RemoveZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).RemoveZone(ctx, req.(*RemoveZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdnsService_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/AddRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).AddRecord(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdnsService_RemoveRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).RemoveRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/RemoveRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).RemoveRecord(ctx, req.(*RemoveRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdnsService_UpdateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).UpdateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/UpdateRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).UpdateRecord(ctx, req.(*UpdateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdnsService_GetDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).GetDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/GetDomains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).GetDomains(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdnsService_GetRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdnsServiceServer).GetRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PdnsService/GetRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdnsServiceServer).GetRecords(ctx, req.(*GetRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PdnsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PdnsService",
	HandlerType: (*PdnsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ping",
			Handler:    _PdnsService_Ping_Handler,
		},
		{
			MethodName: "createAccount",
			Handler:    _PdnsService_CreateAccount_Handler,
		},
		{
			MethodName: "getToken",
			Handler:    _PdnsService_GetToken_Handler,
		},
		{
			MethodName: "changePassword",
			Handler:    _PdnsService_ChangePassword_Handler,
		},
		{
			MethodName: "initZone",
			Handler:    _PdnsService_InitZone_Handler,
		},
		{
			MethodName: "removeZone",
			Handler:    _PdnsService_RemoveZone_Handler,
		},
		{
			MethodName: "addRecord",
			Handler:    _PdnsService_AddRecord_Handler,
		},
		{
			MethodName: "removeRecord",
			Handler:    _PdnsService_RemoveRecord_Handler,
		},
		{
			MethodName: "updateRecord",
			Handler:    _PdnsService_UpdateRecord_Handler,
		},
		{
			MethodName: "getDomains",
			Handler:    _PdnsService_GetDomains_Handler,
		},
		{
			MethodName: "getRecords",
			Handler:    _PdnsService_GetRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
