name: main

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
    - name: Lint
     run: golint -set_exit_status main
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build 
      run: cd testing && docker-compose up --build -d
    - name: Test
      run: cd testing && docker-compose exec -T grpc go test ./testing
    - name: Test2
      run: cd testing && docker-compose exec -T grpc go clean -testcache && docker-compose exec -T grpc go test ./testing